=== fpinero/test_helm_nats_with_tls/k8smain-saas-es-westeurope-dev/platform-management/overlays/qa/config/config-schema.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "bizerba-config-schema",
    "title": "Bizerba configuration settings schema",
    "type": "object",
    "definitions": {
        "versionInfo": {
            "type": "object",
            "description": "Entity version",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Version name"
                },
                "versionNumber": {
                    "type": "string",
                    "description": "Version number"
                }
            },
            "required": ["name", "versionNumber"]
        }
    },
    "properties": {
        "serverURL": {
            "type": "string",
            "description": "Server URL for REST calls"
        },
        "restApiVersion": {
            "type": "string",
            "description": "Rest API Version used in the application"
        },
        "availableLanguages": {
            "type": "array",
            "default": ["en_US", "en", "de"],
            "description": "List of available languages"
        },
        "defaultLanguage": {
            "type": "string",
            "default": "en-US",
            "description": "Default application's language"
        },
        "wsURL": {
            "type": "string",
            "description": "WS Url for SignalR connection"
        },
        "logOutURL": {
            "type": "string",
            "description": "Url log out"
        },
        "versioning": {
            "type": "array",
            "description": "List of versions",
            "items": {
                "$ref": "#/definitions/versionInfo"
            }
        }
    },
    "required": [
        "serverURL",
        "restApiVersion",
        "availableLanguages",
        "defaultLanguage",
        "wsURL",
        "logOutURL",
        "versioning"
    ]
}

=== fpinero/test_helm_nats_with_tls/k8smain-saas-es-westeurope-dev/platform-management/overlays/dev/config/config.json
{
  "$schema": "./config-schema.json",
  "serverURL": "https://bizerba-bss-dev.com/",
  "defaultLanguage": "en-US",
  "availableLanguages": [
    "de",
    "en",
    "en-US"
  ],
  "restApiVersion": "1",
  "wsURL": "https://bizerba-bss-dev.com/notificationHub/notificationHub",
  "logOutURL": "https://bizerba-bss-dev.com/logout",
  "versioning": [
    {
      "name": "biss-saas-fe",
      "versionNumber": "20220527.1"
    },
    {
      "name": "mtm-api",
      "versionNumber": "0.2.0.7"
    },
    {
      "name": "notificationservice",
      "versionNumber": "0.0.2"
    }
  ]
}

=== fpinero/test_helm_nats_with_tls/K8s-dev-saas-westeurope/tenant-management/overlays/qa/config/config.json
{
  "$schema": "./config-schema.json",
  "serverURL": "https://bizerba-bss-qa.com/",
  "defaultLanguage": "en-US",
  "availableLanguages": [
    "de",
    "en",
    "en-US"
  ],
  "restApiVersion": "1",
  "wsURL": "https://bizerba-bss-qa.com/notificationHub/notificationHub",
  "logOutURL": "https://bizerba-bss-qa.com/logout",
  "versioning": [
    {
      "name": "biss-saas-fe",
      "versionNumber": "20220527.1"
    },
    {
      "name": "mtm-api",
      "versionNumber": "0.2.0.7"
    },
    {
      "name": "notificationservice",
      "versionNumber": "0.0.2"
    }
  ]
}

=== fpinero/test_helm_nats_with_tls/K8s-dev-saas-westeurope/platform-management/0.1.0.157/localhost/config/config.json
{
    "$schema": "../../../../schemas/config-schema.json",
    "serverURL": "http://localhost:8888/",
    "defaultLanguage": "en-US",
    "availableLanguages": ["de", "en", "en-US"],
    "restApiVersion": "1",
    "wsURL": "http://localhost:8080/notificationHub",
    "logOutURL": "https://bizerbab2cdev.b2clogin.com/bizerbab2cdev.onmicrosoft.com/b2c_1a_signup_signin2_es/oauth2/v2.0/logout?post_logout_redirect_uri=https://bizerba-bss-low.com",
    "versioning": [
        { "name": "biss-saas-fe", "versionNumber": "0.1.0.157" },
        { "name": "mtm-api", "versionNumber": "RC-0.3.0.24" },
        { "name": "notificationservice", "versionNumber": "0.0.2" }
    ]
}

=== fpinero/test_helm_nats_with_tls/K8s-dev-saas-westeurope/tenant-management/overlays/devops/config/config.json
{
    "$schema": "./config-schema.json",
    "serverURL": "https://bizerba-bss-dev.com/",
    "defaultLanguage": "en-US",
    "availableLanguages": ["de", "en", "en-US"],
    "restApiVersion": "1",
    "wsURL": "https://bizerba-bss-dev.com/notificationHub/notificationHub",
    "logOutURL": "https://bizerba-bss-dev.com/logout",
    "versioning": [
        { "name": "tenant-management", "versionNumber": "0.1.0.53" },
        { "name": "mtm-api", "versionNumber": "RC-0.3.0.19" },
        { "name": "notificationservice", "versionNumber": "0.0.2" }
    ]
}

=== fpinero/test_helm_nats_with_tls/k8smain-saas-es-westeurope-dev/tenant-management/overlays/low/config/config.json
{
  "$schema": "./config-schema.json",
  "serverURL": "http://localhost:8888/",
  "defaultLanguage": "en-US",
  "availableLanguages": [
    "de",
    "en",
    "en-US"
  ],
  "restApiVersion": "1",
  "wsURL": "https://bizerba-bss-low.com/notificationHub/notificationHub",
  "logOutURL": "https://bizerba-bss-low.com/logout",
  "versioning": [
    {
      "name": "biss-saas-fe",
      "versionNumber": "20220527.1"
    },
    {
      "name": "mtm-api",
      "versionNumber": "0.2.0.7"
    },
    {
      "name": "notificationservice",
      "versionNumber": "0.0.2"
    }
  ]
}

=== fpinero/test_helm_nats_with_tls/K8s-dev-saas-westeurope/platform-management/0.1.0.297/localhost/config/config.json
{
    "$schema": "../../../../schemas/config-schema.json",
    "serverURL": "https://bizerba-bss-dev.com/",
    "defaultLanguage": "en-US",
    "availableLanguages": ["de", "en", "en-US"],
    "restApiVersion": "1",
    "wsURL": "https://bizerba-bss-dev.com/notificationHub/notificationHub",
    "logOutURL": "https://bizerbab2cdev.b2clogin.com/bizerbab2cdev.onmicrosoft.com/b2c_1a_signup_signin2_es/oauth2/v2.0/logout?post_logout_redirect_uri=https://bizerba-bss-low.com",
    "versioning": [
        { "name": "biss-saas-fe", "versionNumber": "20220527.1" },
        { "name": "mtm-api", "versionNumber": "0.2.0.7" },
        { "name": "notificationservice", "versionNumber": "0.0.2" }
    ]
}
